# Copyright Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: MIT

"""Generate the playbook and AMD-hardware dropdowns in the issue forms.

The issue forms ask which playbook a problem is about and which AMD hardware it
was seen on. Free-text answers cannot be routed, so the options are generated
from the source of truth and kept in sync by a CI check:

* Playbook options come from the playbooks themselves. Only `core` and
  `supplemental` are listed; `backup` holds drafts readers cannot reach.
* Hardware options come from .github/scripts/device_registry.json, so a new
  device is added in one place and every form updates.

Generated regions are spliced between marker comments, leaving everything else
(including the trailing "Other AMD hardware" / "Something else" options) intact.

Usage:
    python .github/scripts/gen_issue_template_playbooks.py            # rewrite
    python .github/scripts/gen_issue_template_playbooks.py --check    # CI drift check
"""

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
PLAYBOOKS_ROOT = REPO_ROOT / "playbooks"
TEMPLATE_DIR = REPO_ROOT / ".github" / "ISSUE_TEMPLATE"
BUG_REPORT = TEMPLATE_DIR / "bug_report.yml"
PLAYBOOK_PROPOSAL = TEMPLATE_DIR / "playbook_proposal.yml"
DEVICE_REGISTRY = REPO_ROOT / ".github" / "scripts" / "device_registry.json"

CATEGORIES = ["core", "supplemental"]
INDENT = " " * 8

PLAYBOOK_BEGIN = "# BEGIN generated by .github/scripts/gen_issue_template_playbooks.py"
PLAYBOOK_END = "# END generated"
DEVICE_BEGIN = "# BEGIN generated devices by .github/scripts/gen_issue_template_playbooks.py"
DEVICE_END = "# END generated devices"


def playbook_options() -> list[str]:
    """Return one `id - Title` option per reachable playbook, sorted by id."""
    entries = []
    for category in CATEGORIES:
        for meta_path in sorted((PLAYBOOKS_ROOT / category).glob("*/playbook.json")):
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
            entries.append((meta["id"], meta["title"]))
    if not entries:
        sys.exit(f"error: no playbooks found under {PLAYBOOKS_ROOT}")
    return [f"{pid} - {title}" for pid, title in sorted(entries)]


def device_options() -> list[str]:
    """Return one `tag - Name` option per device, in registry order."""
    registry = json.loads(DEVICE_REGISTRY.read_text(encoding="utf-8"))
    devices = registry.get("devices", [])
    if not devices:
        sys.exit(f"error: no devices found in {DEVICE_REGISTRY}")
    return [f"{d['tag']} - {d['name']}" for d in devices]


def splice(current: str, options: list[str], begin: str, end: str, path: Path) -> str:
    """Replace the option list between the markers, leaving the rest untouched."""
    lines = current.splitlines(keepends=True)
    try:
        b = next(i for i, line in enumerate(lines) if line.strip() == begin)
        e = next(i for i, line in enumerate(lines) if line.strip() == end)
    except StopIteration:
        sys.exit(f"error: missing '{begin}' / '{end}' markers in {path}")
    if e < b:
        sys.exit(f"error: end marker precedes begin marker in {path}")
    # json.dumps emits a double-quoted scalar that YAML reads the same way, so a
    # title containing ": " or a leading "-" cannot break the document.
    body = [f"{INDENT}- {json.dumps(opt, ensure_ascii=False)}\n" for opt in options]
    return "".join(lines[: b + 1] + body + lines[e:])


def build(path: Path, playbooks: list[str] | None, devices: list[str] | None) -> str:
    """Return the rewritten file content for the given target regions."""
    updated = path.read_text(encoding="utf-8")
    if playbooks is not None:
        updated = splice(updated, playbooks, PLAYBOOK_BEGIN, PLAYBOOK_END, path)
    if devices is not None:
        updated = splice(updated, devices, DEVICE_BEGIN, DEVICE_END, path)
    return updated


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if any form is out of date instead of rewriting it.",
    )
    args = parser.parse_args()

    playbooks = playbook_options()
    devices = device_options()

    # bug_report.yml has both the playbook and device dropdowns;
    # playbook_proposal.yml has only the device dropdown (no playbook exists yet).
    targets = [
        (BUG_REPORT, playbooks, devices),
        (PLAYBOOK_PROPOSAL, None, devices),
    ]

    stale = False
    for path, pb, dev in targets:
        current = path.read_text(encoding="utf-8")
        updated = build(path, pb, dev)
        rel = path.relative_to(REPO_ROOT).as_posix()
        if current == updated:
            print(f"OK: {rel} is up to date.")
            continue
        stale = True
        if args.check:
            diff = difflib.unified_diff(
                current.splitlines(keepends=True),
                updated.splitlines(keepends=True),
                fromfile=f"a/{rel}",
                tofile=f"b/{rel}",
            )
            print(f"ERROR: {rel} is out of date.")
            print("Run: python .github/scripts/gen_issue_template_playbooks.py")
            print()
            print("".join(diff), end="")
        else:
            path.write_text(updated, encoding="utf-8", newline="\n")
            print(f"Updated {rel}.")

    if args.check and stale:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
